spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/yupi
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
server:
  port: 8080

